#############################################################################
# Makefile for building: qtwebglplugin
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  qtwebglplugin.pro
# Template: subdirs
# Command: /home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/qmake -o Makefile qtwebglplugin.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/kristof/Qt5.10.0/5.10.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtwebglplugin1.0.0
DISTDIR = /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/.obj/qtwebglplugin1.0.0
SUBTARGETS    =  \
		sub-src \
		sub-tests


sub-src-qmake_all:  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro
	cd src/ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all: sub-src-qmake_all FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro
	cd tests/ && $(MAKE) -f Makefile qmake_all
sub-tests: sub-src FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro ) && $(MAKE) -f Makefile
sub-tests-make_first: sub-src-make_first FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro ) && $(MAKE) -f Makefile 
sub-tests-all: sub-src-all FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro ) && $(MAKE) -f Makefile all
sub-tests-clean: sub-src-clean FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro ) && $(MAKE) -f Makefile clean
sub-tests-distclean: sub-src-distclean FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets: sub-src-install_subtargets FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets: sub-src-uninstall_subtargets FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro ) && $(MAKE) -f Makefile uninstall

Makefile: qtwebglplugin.pro .qmake.conf .qmake.cache /home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf /home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/spec_pre.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/unix.conf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/linux.conf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/sanitize.conf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/gcc-base.conf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/g++-base.conf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/g++-unix.conf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/qconfig.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		mkspecs/modules-inst/qt_plugin_qwebgl.pri \
		mkspecs/modules/qt_plugin_qwebgl.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_functions.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_config.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/spec_post.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/qmodule.pri \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_build_config.prf \
		.qmake.conf \
		.qmake.cache \
		.qmake.stash \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/toolchain.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/default_pre.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_configure.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_parts.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/resolve_config.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/default_post.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/exceptions_off.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_example_installs.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_docs_targets.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/precompile_header.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/unix/largefile.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/warn_on.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qmake_use.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/file_copies.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_build_extra.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/yacc.prf \
		/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/lex.prf \
		qtwebglplugin.pro
	$(QMAKE) -o Makefile qtwebglplugin.pro
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/spec_pre.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/unix.conf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/linux.conf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/sanitize.conf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/gcc-base.conf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/g++-base.conf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/common/g++-unix.conf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/qconfig.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
mkspecs/modules-inst/qt_plugin_qwebgl.pri:
mkspecs/modules/qt_plugin_qwebgl.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_functions.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_config.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/spec_post.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/qmodule.pri:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_build_config.prf:
.qmake.conf:
.qmake.cache:
.qmake.stash:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/toolchain.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/default_pre.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_configure.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_parts.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/resolve_config.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/default_post.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/exceptions_off.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_example_installs.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_docs_targets.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/precompile_header.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/unix/largefile.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/warn_on.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qmake_use.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/file_copies.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/qt_build_extra.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/testcase_targets.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/yacc.prf:
/home/kristof/Qt5.10.0/5.10.0/gcc_64/mkspecs/features/lex.prf:
qtwebglplugin.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile qtwebglplugin.pro

qmake_all: sub-src-qmake_all sub-tests-qmake_all FORCE

make_first: sub-src-make_first  FORCE
all: sub-src-all sub-tests-all  FORCE
clean: sub-src-clean sub-tests-clean  FORCE
distclean: sub-src-distclean sub-tests-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.cache config.cache config.log mkspecs/modules/*.pri mkspecs/modules-inst/*.pri .qmake.stash
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

sub-src-install_html_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile install_html_docs
install_html_docs: sub-src-install_html_docs

sub-src-uninstall_html_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile uninstall_html_docs
uninstall_html_docs: sub-src-uninstall_html_docs

sub-src-install_qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile install_qch_docs
install_qch_docs: sub-src-install_qch_docs

sub-src-uninstall_qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile uninstall_qch_docs
uninstall_qch_docs: sub-src-uninstall_qch_docs

sub-src-install_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile install_docs
install_docs: sub-src-install_docs

sub-src-uninstall_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile uninstall_docs
uninstall_docs: sub-src-uninstall_docs

sub-src-qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile qch_docs
qch_docs: sub-src-qch_docs

sub-src-prepare_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile prepare_docs
prepare_docs: sub-src-prepare_docs

sub-src-generate_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile generate_docs
generate_docs: sub-src-generate_docs

sub-src-check:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile check
check: sub-src-check

sub-src-benchmark:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-src-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-src-distdir sub-tests-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents mkspecs/modules-inst/qt_plugin_qwebgl.pri mkspecs/modules/qt_plugin_qwebgl.pri .qmake.conf .qmake.stash qtwebglplugin.pro $(DISTDIR)/

sub-src-distdir: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/src/src.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/src

sub-tests-distdir: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/kristof/Qt5.10.0/5.10.0/gcc_64/qtwebglplugin/tests/tests.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/tests

